### PR TITLE
CSV Import no longer requires 'email' to be case sensitive, can be written with a dash e.g. E-mail

### PR DESCRIPTION
**Pull request by lukecamelo**
It seems the reason it could not accept variations of the word email is due to client side validation on the ImportCSV component. I just added some simple conditional logic that allows all reasonable variations of E-mail to be valid.

### CODE REVIEW

**Comment by lukecamelo** [comment]
Hey so I did my best to undo those changes, but I'm not sure if I did so properly. I've never had to rewrite a branch's history before. If I made a mistake please let me know so I can do it properly.

**Comment by zhakkarn** [comment]
I'm not exactly sure of what you did.

Squashing your PR before merging would be clean enough. Should I do it or should I leave you the opportunity to try your hand at reseting and make this PR all shiny and squeaky clean?

Here is what I'm proposing you to try:
Before anything, make a copy of your mail-for-good directory, just in case. You can go with ```git reset HEAD~X``` where 'X' is the number the commits you want to erase. Unless you use ```git reset --hard <path>``` you will keep your changes, just not your commits, leaving you in a position to redo your commits.
After that, commit only "client/containers/lists/ImportCSV.js" and here you have the most meaningful and concise PR.

I'm most likely a maniac and I should squash then merge. I'm just convinced that if the history is clean enough it leads to everyone understanding who did what, how it was done and why.

**Comment by lukecamelo** [comment]
I did what you recommended and it seems the old commits are still on file. I think it's looking like I'm too much of a git noob to pull this off cleanly. Sorry, I tried my best to fix it! And also sorry for not going for it for 8 days haha.

**Comment by zhakkarn** [comment]
> Sorry, I tried my best to fix it!  

Alright, you tried your best. I'll merge it thank you for your time and effort toward solving this issue.

> sorry for not going for it for 8 days haha. 
 
\<Sarcasm\>See, I'm pretty sure that everyone who did interact with this repo knows by know that I'm fast to answer, so yeah, you better be sorry.\</Sarcasm\>

**Pull request merged**
