### PR TITLE
Fix/login page redirects to main when authenticated

### PR DESCRIPTION
**Pull request by HassanAli321**
Please check this pr and let me know there is anything to change

### CODE REVIEW

**Comment by zhakkarn** [comment]
Hi @HassanAli321 ,
Thank you for making your first PR to mail for good.

I do have two questions : 
-Do we really need to add 27k lines of code to make your solution work?
-Why do you propose clearing the cache and store of a non-authenticated user queries the login page? If the user isn't authenticated wouldn't there be nothing to clear anyway?

**Comment by HassanAli321** [comment]
i don't know why there is 27k line of code change there is may be some mistake i just only change 5 to 6 lines

**Comment by HassanAli321** [comment]
I think this is the quick fix for the time because i see a issue in which you said that the whole user login flow needs to change from google login to simple email password is it right ?

**Comment by zhakkarn** [comment]
I might get you wrong so I'll reformulate what I'm understanding and I let you correct me. You want the login page out of the user's cache in order to force a logged user to query the server instead of the potentially cached login page.

Also, this is not a quick fix. You are using a middleware provided by passport.js to check if the user is logged or not. This middleware is independent of the used strategy so this will be working before and after the change of flow/strategy.

**Comment by AndrewGHC** [comment]
Hey @HassanAli321,

Thanks for your effort with this PR. Your commit log contains commits that are behind the current head, so we won't be able to merge this. Could you rebase your changes on top of the master branch? Thanks.

**Pull request closed without merging**
