### PR TITLE
gh-pages: initial commit

### PR DESCRIPTION
**Pull request by seanWLawrence**
Issue# 170: This is the first version of the GitHub Pages site. It's written with [Hugo](https://gohugo.io/) and uses the [Hugo Material Docs Theme](https://github.com/digitalcraftsman/hugo-material-docs).

Please advise if I need to make any changes for the pull request, this is my first one.

### CODE REVIEW

**Comment by zhakkarn** [comment]
Could you link me to the documentation you used to understand how github pages works? I've never deployed documentation this way before. I checked to your branch and I'd like to be a little less lost in when looking at what you've done and how.

**Comment by seanWLawrence** [comment]
@zhakkarn Sorry for the confusion, I thought it'd be easy to deploy it from a separate branch that only contains the website code so it doesn't get downloaded when the master repo is cloned. 

How would you like me to add the website? I want to make it as easy as possible for you. 

Perhaps in a /docs folder in the root folder instead?

**Comment by zhakkarn** [comment]
@seanWLawrence Ok, now I understand where you are coming from.
The problem is, git doesn't work like that.
You don't commit files in the same way that you upload on your cloud storage solution. A commit describes the changes you've made either by adding or deleting lines/files. 
In your branch you deleted all the mail-for-good sources, which is a change compared to what you received when you cloned the repo. So this means that if I was to merge your branch to staging, boom all the stuff you deleted, they are deleted on staging as well. You can see that in your PR under the "files changed" tab your are proposing to delete a heavy amount of code.

Another problem is that your branch is made of 11 commits but 10 of them are already part of the staging branch. The best way I can see to clean your PR would be to rebase your branch onto the head of staging (well, rebase it on the head of master and then remake your PR from your branch to master. You are submitting doc so you are not going to break the app's code. We can merge it to the master branch right away)

I like way more the idea of putting your website in /docs as I can imagine it would be confusing for newcomers to see the index.html, "layouts", "content", "static" folders and so on sitting in the root directory of the project. I can see coming that some of them will think that it is part of mail-for-good instead of its documentation platform.

So, what I'm suggesting is you clone the mail-for-good repo to get a fresh local repo. From there you create a branch from master. You checkout to this branch then you change what you want to see changed in the repo i.e you move around the content of /docs to make it as it is going to be on the repo. Once you are satisfied commit to this previously created branch then submit a PR from this branch to freecodecamp/master.

Disclaimer: my English isn't good enough for me to manipulate the tone I use nor to guarantee that I was clear in what I tried to say so I'm sorry if I was confusing or appeared to be ungratteful.

**Comment by zhakkarn** [comment]
@seanWLawrence , if you want, we can schedule a skype/discord call to help you make your pull request.

**Comment by seanWLawrence** [comment]
Thank you so much for your explanation, that makes perfect sense and I'll e a new PR tonight following your instructions. Do I need to do anything with this faulty pull request from my end to cancel it?

**Comment by seanWLawrence** [comment]
@zhakkarn Thank you so much for your explanation and guidance - I really appreciate it. 

As instructed, I created another PR (#251) by simply cloning the master branch and then adding the site to `/docs/gh-pages` (without changing anything else) and then switched the pull request to merge with the master branch, instead of the staging branch. Is this correct, and do I need to do anything with this pull request (#248) that I messed up?

PS. Please forgive me if I misunderstood you. I've read the instructions on the contributing guidelines and your last message repeatedly and if I'm still doing this totally wrong and you think it'd be easier to get this done over a call, I'd be happy to hop on real quick sometime this week - I want to make it as easy as possible for you and the team.

Thanks again!

**Comment by zhakkarn** [comment]
This pull request will be closed and the discussion will continue on the new one.

**Pull request closed without merging**
