### PR TITLE
When creating mailing list allow user to use meaningful name

### PR DESCRIPTION
**Pull request by zhakkarn**
These changes allow a user to rename his lists.

The lists also don't get a default name on import so the user won't be tempted to roll with timestamps and get confused down the road when he'll have to juggle with 4-5 lists bearing timestamps as a name.

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Hey @zhakkarn , everything works fine for you ? While importing lists ? Because I was having issues with importing #149

**Comment by zhakkarn** [comment]
Hi @karuppiah7890. I ran into the same problem as you are describing. 

@AndrewGHC told that it was due to the updates made to the modules (he mentioned node-csv I believe) and for now a fine fix consists of reverting the version.

**Comment by karuppiah7890** [comment]
@zhakkarn Can you tell me what the fix is ? And I don't see any node-csv module, please enlighten me :)

**Comment by zhakkarn** [comment]
@karuppiah7890 @AndrewGHC  After some research it appears that upgrading sequelize to 4.x is the cause of the problem.

**Comment by karuppiah7890** [comment]
Yes, I saw lots of major version updates. Hopefully others won't cause any issues I guess ?

**Pull request merged**
